version: "3"

services:


  education:
    image: hub.docker.com/r/termyter1/back:education
    ports:
      - "3001:3001"
    environment:
      SERVICE_NAME: education
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure


  user:
    build:
      context: User
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      SERVICE_NAME: user
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  gateway:
    image: termyter1/back:gateway
    build:
      context: ./Gateway
    links:
      - User
      - educatuion
    ports:
      - 8080:80
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure


